[package]
name = "watchdescriptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
log = "0.4"
serde = "1.0.159"
serde_json = "1.0.72"
cln-plugin = { git = "https://github.com/chrisguida/lightning", version = "0.1.2", branch = "feat/cln-plugin-send-notifs" }
# cln-plugin = { path = "../../lightning/plugins" }
bdk = "0.27.1"

[dependencies.tokio]
features = ["net", "rt-multi-thread"]
version = "1"
